name: Prepare Xcode build
inputs:
  access_token:
    description: "The GitHub access token"
    required: true
  submodules:
    description: "Fetch submodules"
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Use HTTPS
      shell: bash
      run: |
        git config --global url.https://github.com/.insteadOf git@github.com:
    - name: Fetch repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.access_token }}
        submodules: ${{ inputs.submodules }}
    - name: Set token in Git Credential helper
      shell: bash
      run: |
        git config --global credential.helper \
        '!f() { echo "username=x-access-token"; echo "password=${{ inputs.access_token }}"; }; f'
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.1
