name: Prepare Xcode build
inputs:
  access_token:
    description: "The GitHub access token"
    required: true
  submodules:
    description: "Fetch submodules"
    required: false
    default: false
runs:
  using: composite
  steps:
    - name: Inject HTTPS token
      shell: bash
      run: |
        git config --global url."https://${{ inputs.access_token }}@github.com/".insteadOf "https://github.com/"
    - name: Fetch repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.access_token }}
        submodules: ${{ inputs.submodules }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.1
