name: Prepare Xcode build
inputs:
  access_token:
    description: "The GitHub access token"
    required: true
runs:
  using: composite
  steps:
    - name: Use HTTPS
      shell: bash
      run: |
        git config --global url.https://github.com/.insteadOf git@github.com:
    - uses: actions/checkout@v4
      with:
        token: ${{ inputs.access_token }}
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.1
