name: Prepare Xcode build
inputs:
  access-token:
    description: "The GitHub access token"
    required: false
  submodules:
    description: "Fetch submodules"
    required: false
    default: false
  certificates-url:
    description: "The URL to the certificates ZIP"
    required: false
  certificates-passphrase:
    description: "The encryption passphrase of the certificates ZIP"
    required: false
runs:
  using: composite
  steps:
    - name: Inject HTTPS token
      shell: bash
      if: ${{ inputs.access-token }}
      run: |
        git config --global url."https://${{ inputs.access-token }}@github.com/".insteadOf "git@github.com:"
    - name: Fetch repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.access-token || github.token }}
        submodules: ${{ inputs.submodules }}
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 26.1
    - name: Install certificates
      shell: bash
      if: ${{ inputs.certificates-url }}
      env:
        ACCESS_TOKEN: ${{ inputs.access-token }}
        CERTIFICATES_URL: ${{ inputs.certificates-url }}
        CERTIFICATES_PASSPHRASE: ${{ inputs.certificates-passphrase }}
      run: |
        ${{ github.action_path }}/install-certificates.sh
    - name: Skip macro validation
      shell: bash
      run: |
        ${{ github.action_path }}/skip-macro-validation.sh
