name: Prepare Xcode build
inputs:
  access_token:
    description: "The GitHub access token"
    required: true
  submodules:
    description: "Fetch submodules"
    required: false
    default: false
  certificates_url:
    description: "The URL to the certificates ZIP"
    required: false
  certificates_passphrase:
    description: "The encryption passphrase of the certificates ZIP"
    required: false
runs:
  using: composite
  steps:
    - name: Inject HTTPS token
      shell: bash
      run: |
        git config --global url."https://${{ inputs.access_token }}@github.com/".insteadOf "git@github.com:"
    - name: Fetch repository
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.access_token }}
        submodules: ${{ inputs.submodules }}
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16.3
    - name: Install certificates
      shell: bash
      if: ${{ inputs.certificates_url }}
      env:
        ACCESS_TOKEN: ${{ inputs.access_token }}
        CERTIFICATES_URL: ${{ inputs.certificates_url }}
        CERTIFICATES_PASSPHRASE: ${{ inputs.certificates_passphrase }}
      run: |
        ${{ github.action_path }}/install-certificates.sh
